name: build-windows
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Source Code Repository
        uses: actions/checkout@v4

      - name: Initialize .NET SDK Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Execute Trimmed Single-File Compilation
        run: dotnet publish KarzaConsolidator.csproj -c Release -r win-x64 --self-contained true -o ./publish

      - name: Package Optimized Binary Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KarzaEngine-Trimmed-Win64
          path: ./publish/*.exe
